version: '3'

networks:
  my_network:

volumes:
  nextcloud:
  db:
  redis_data:

services:
  #--------------------------------------------
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    networks:
      - my_network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
    volumes:
      - db:/var/lib/mysql
  #--------------------------------------------
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - my_network
    volumes:
      - redis_data:/data
  #--------------------------------------------
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    #build: .
    networks:
      - my_network
    restart: always
    ports:
      - "8080:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - nextcloud:/var/www/html
  #--------------------------------------------
  locust:
    image: locustio/locust
    container_name: locust
    command: -f /locust-tests/locustfile.py --host http://nextcloud:80
    ports:
      - "8089:8089"
    volumes:
      - ./locust-tests:/locust-tests
      - ./data:/data
    depends_on:
      - nextcloud
    networks:
      - my_network
 
  #--------------------------------------------
